GET http://localhost:3000/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjU4NjcyMTk1LCJleHAiOjE2NTg2NzIyMTV9.fcRJOQpxOvx1o5UElCPbd9xVdesA1zEc7gBeQAIAlQs

###
DELETE http://localhost:4000/logout 
Content-Type: application/json

{
 "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjU4NjcyMTYzfQ.i8wXSuGi6wP3_vNoXSAFhxY_laqMTh-1JJy5P6GX-VY"
}

###
POST http://localhost:4000/token 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjU4NjcyMTYzfQ.i8wXSuGi6wP3_vNoXSAFhxY_laqMTh-1JJy5P6GX-VY"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
 "username": "Jim"
}